#!/bin/bash
set -eu -o pipefail

NOC='\033[0m'
GRN='\033[0;32m'
YLW='\033[0;33m'

image_name="docker-build-cpp"
container_name="cpp-proj"
target_path="/proj"
build_dir="build"

# stop the container if it is running ------------------------
if [[ $(docker ps --filter "name=^/${container_name}$" --format '{{.Names}}') == "${container_name}" &&
"$(docker container inspect -f '{{.State.Running}}' ${container_name})" == "true" ]]; then
    echo -e "${YLW}Stop container \"${container_name}\"${NOC} ..."
    docker stop ${container_name}
fi

# remove the container if it exists but not running ------------------------
if [[ $(docker ps --filter "name=^/${container_name}$" --format '{{.Names}}') == "${container_name}" ]]; then
    echo -e "${YLW}Remove container \"${container_name}\"${NOC} ..."
    docker rm ${container_name}
fi

# build an image from Dockerfile ------------------------
echo -e "${GRN}Build the image \"${image_name}\"${NOC} ..."
DOCKER_BUILDKIT=1 docker build \
    -t ${image_name} \
    -f docker/Dockerfile docker

# create a container and run it ------------------------
echo -e "${GRN}Run container \"${container_name}\" from image \"${image_name}\"${NOC} ..."
docker run -d -it --rm \
    --name ${container_name} \
    --mount type=bind,source="$(pwd)",target=${target_path} \
    ${image_name}

# build the project in the container ------------------------
# ${target_path} ${build_dir}: arguments passed into ./docker/build
echo -e "${GRN}Build the project${NOC} ..."
docker exec ${container_name} ${target_path}/docker/build \
    ${target_path} ${build_dir}

# play some tricky  ------------------------
if [ -d ${build_dir} ]; then
    sudo chown $(whoami):$(whoami) ${build_dir} -R
fi
echo -e "${GRN}Project is build successfully.${NOC}"
